-- MySQL Script generated by MySQL Workbench
-- Tue May  5 19:42:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordermanagement` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ordermanagement
-- -----------------------------------------------------
USE `ordermanagement` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordermanagement`.`Client` (
  `Name` VARCHAR(100) NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordermanagement`.`Product` (
  `Name` VARCHAR(45) NOT NULL,
  `Amount` INT NULL,
  `Price` FLOAT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordermanagement`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `ClientName` VARCHAR(100) NULL,
  `ProductName` VARCHAR(45) NULL,
  `ProductAmount` INT NULL,
  `OrderPrice` Float NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Order_Client_idx` (`ClientName` ASC) ,
  INDEX `fk_Order_Product1_idx` (`ProductName` ASC) ,
  CONSTRAINT `fk_Order_Client`
    FOREIGN KEY (`ClientName`)
    REFERENCES `ordermanagement`.`Client` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`ProductName`)
    REFERENCES `ordermanagement`.`Product` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE USER 'user'@'localhost';
#GRANT ALL PRIVILEGES ON ordermanagement.* To 'user'@'localhost' IDENTIFIED BY 'password';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
